name: Build

on:
  push:
    branches-ignore:
      - 'l10n_master'
      - 'gh-pages'
  release:
    types:
      - published

jobs:

  cloc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Set up cloc
        run: |
          sudo apt-get update
          sudo apt-get -y install cloc

      - name: Print lines of code
        run: cloc --vcs git --exclude-dir Resources,store,test,Properties --include-lang C#,XAML

  android:
    runs-on: windows-latest

    steps:
      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@c26a08ba26249b81327e26f6ef381897b6a8754d

      - name: Print environment
        run: |
          nuget help | grep Version
          msbuild -version
          dotnet --info
          echo "GitHub ref: $GITHUB_REF"
          echo "GitHub event: $GITHUB_EVENT"
        env:
          GITHUB_REF: ${{ github.ref }}
          GITHUB_EVENT: ${{ github.event_name }}

      - name: Checkout repo
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Increment version
        if: github.ref == 'refs/heads/master' || github.event_name == 'release'
        run: ./.github/scripts/android/increment-version.ps1
        shell: pwsh

      - name: Restore packages
        run: nuget restore

      - name: Run Core Tests
        run: dotnet test test/Core.Test/Core.Test.csproj

      - name: Clean for F-Droid
        run: ./.github/scripts/android/clean-fdroid.ps1
        shell: pwsh

      - name: Restore packages
        run: nuget restore

      - name: Build for Release
        run: ./.github/scripts/android/build.ps1 -configuration Release
        shell: pwsh
      
      - name: Get build name
        run: dir ./src/Android/bin/Release
        shell: pwsh
